Algoritmo "sem_nome"

Var
   numero, soma, par, impar, i: inteiro
   resultado: real
Inicio
   para i de 1 até 20 passo 2 faca
      escreval ("Digite um número:")
      leia (numero)
      se (numero mod 2) = 0 entao
         escreval ("Este número é par")
         par <- i + 1
      senao
         escreval ("Este número é ímpar")
         impar <- i + 2
      fimse
  fimpara
      escreval ("Agora vamos somar cada conjunto"
Fimalgoritmo